// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrkovwuraehejkiiwhbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFya292d3VyYWVoZWpraWl3aGJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MDg1NDMsImV4cCI6MjA1NTk4NDU0M30.FS3qfzl55TQKnorMfJkHB9j5wzx-sQTKiqx__eBKMpk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);